#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Guard
Version  : 1.023
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Guard-1.023.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Guard-1.023.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libg/libguard-perl/libguard-perl_1.023-1.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Guard-lib
Requires: perl-Guard-license
Requires: perl-Guard-man

%description
NAME
Guard - safe cleanup blocks
SYNOPSIS
use Guard;

# temporarily chdir to "/etc" directory, but make sure
# to go back to "/" no matter how myfun exits:
sub myfun {
scope_guard { chdir "/" };
chdir "/etc";

code_that_might_die_or_does_other_fun_stuff;
}

%package lib
Summary: lib components for the perl-Guard package.
Group: Libraries
Requires: perl-Guard-license

%description lib
lib components for the perl-Guard package.


%package license
Summary: license components for the perl-Guard package.
Group: Default

%description license
license components for the perl-Guard package.


%package man
Summary: man components for the perl-Guard package.
Group: Default

%description man
man components for the perl-Guard package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Guard-1.023
mkdir -p %{_topdir}/BUILD/Guard-1.023/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Guard-1.023/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Guard
cp COPYING %{buildroot}/usr/share/doc/perl-Guard/COPYING
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Guard.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Guard/Guard.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Guard/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Guard.3
